/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CallbackTest {
    'clickHandler': Function;
  }
  interface CallbackTestAttributes extends StencilHTMLAttributes {
    'clickHandler'?: Function;
  }

  interface RenderingTest {}
  interface RenderingTestAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CallbackTest': Components.CallbackTest;
    'RenderingTest': Components.RenderingTest;
  }

  interface StencilIntrinsicElements {
    'callback-test': Components.CallbackTestAttributes;
    'rendering-test': Components.RenderingTestAttributes;
  }


  interface HTMLCallbackTestElement extends Components.CallbackTest, HTMLStencilElement {}
  var HTMLCallbackTestElement: {
    prototype: HTMLCallbackTestElement;
    new (): HTMLCallbackTestElement;
  };

  interface HTMLRenderingTestElement extends Components.RenderingTest, HTMLStencilElement {}
  var HTMLRenderingTestElement: {
    prototype: HTMLRenderingTestElement;
    new (): HTMLRenderingTestElement;
  };

  interface HTMLElementTagNameMap {
    'callback-test': HTMLCallbackTestElement
    'rendering-test': HTMLRenderingTestElement
  }

  interface ElementTagNameMap {
    'callback-test': HTMLCallbackTestElement;
    'rendering-test': HTMLRenderingTestElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
